<?php

use App\Models\User;

if (! function_exists('portal_text')) {
    function portal_text(User|string|null $userOrLanguage, string $key): string
    {
        $language = $userOrLanguage instanceof User
            ? $userOrLanguage->language_preference
            : ($userOrLanguage ?: 'en');

        $translations = [
            'en' => [
                'brand' => 'CropDetec',
                'dashboard' => 'Dashboard',
                'upload' => 'Upload',
                'history' => 'History',
                'library' => 'Library',
                'profile' => 'Profile',
                'logout' => 'Log out',
                'hello' => 'Hello, :name.',
                'dashboard_intro' => 'Use this dashboard to upload crop leaf images, review diagnosis results, browse crop disease guidance, and update your farmer profile.',
                'upload_image' => 'Upload image for diagnosis',
                'view_history' => 'View diagnosis history',
                'crop_library' => 'Crop library',
                'dashboard_actions' => 'Main actions',
                'workspace_shortcuts' => 'Workspace shortcuts',
                'operational_areas' => 'Operational areas',
                'upload_image_hint' => 'Take or choose a clear leaf photo and send it for AI-assisted disease checking.',
                'view_history_hint' => 'Review previous diagnosis results, confidence scores, and recommendations.',
                'crop_library_hint' => 'Browse supported crops, disease symptoms, prevention steps, and treatments.',
                'profile_hint' => 'Update your farmer details, phone number, and preferred language.',
                'logout_hint' => 'End this browser session when you are finished using the system.',
                'recent_diagnoses' => 'Recent diagnoses',
                'no_diagnoses' => 'No diagnoses yet. Start by uploading a clear crop leaf image.',
                'date' => 'Date',
                'crop' => 'Crop',
                'disease' => 'Disease',
                'confidence' => 'Confidence',
                'open' => 'Open',
                'upload_crop_image' => 'Upload crop image',
                'upload_intro' => 'Choose a clear photo of the affected leaf. JPG, PNG, and WEBP images up to 5 MB are supported.',
                'first_matching_crop' => 'Let the system use the first matching crop',
                'leaf_image' => 'Leaf image',
                'run_diagnosis' => 'Run diagnosis',
                'disclaimer' => 'Predictions support field decisions but do not replace professional agricultural advice.',
                'diagnosis_history' => 'Diagnosis history',
                'history_intro' => 'Filter previous crop diagnoses by crop, disease, or date.',
                'all_crops' => 'All crops',
                'all_diseases' => 'All diseases',
                'all_dates' => 'All dates',
                'today' => 'Today',
                'last_7_days' => 'Last 7 days',
                'apply_filters' => 'Apply filters',
                'no_matching_diagnoses' => 'No matching diagnoses found.',
                'uploaded_image' => 'Uploaded image',
                'recommendation' => 'Recommendation',
                'low_confidence' => 'Low confidence',
                'low_confidence_advice' => 'Retake the photo in brighter light or consult an extension officer.',
                'upload_another' => 'Upload another image',
                'back_to_history' => 'Back to history',
                'crop_library_intro' => 'Browse supported crops, disease symptoms, prevention guidance, and treatments.',
                'symptoms' => 'Symptoms',
                'prevention' => 'Prevention',
                'profile_intro' => 'Update your farmer details and preferred language.',
                'profile_updated' => 'Profile updated successfully.',
                'full_name' => 'Full name',
                'email_address' => 'Email address',
                'phone_number' => 'Phone number',
                'preferred_language' => 'Preferred language',
                'english' => 'English',
                'shona' => 'Shona',
                'save_profile' => 'Save profile',
                'unknown_crop' => 'Unknown crop',
            ],
            'sn' => [
                'brand' => 'AI Yekuona Zvirwere Zvezvirimwa',
                'dashboard' => 'Dhibhodhi',
                'upload' => 'Isa mufananidzo',
                'history' => 'Nhoroondo',
                'library' => 'Raibhurari',
                'profile' => 'Nhoroondo yako',
                'logout' => 'Buda',
                'hello' => 'Mhoro, :name.',
                'dashboard_intro' => 'Shandisa dhibhodhi iri kuisa mifananidzo yemashizha, kuona mhedzisiro, kuverenga mazano ezvirwere zvezvirimwa, uye kugadzirisa nhoroondo yako.',
                'upload_image' => 'Isa mufananidzo kuti uongororwe',
                'view_history' => 'Ona nhoroondo yekuongororwa',
                'crop_library' => 'Raibhurari yezvirimwa',
                'dashboard_actions' => 'Zvaunogona kuita',
                'workspace_shortcuts' => 'Nzira pfupi dzebasa',
                'operational_areas' => 'Nzvimbo dzekushandira',
                'upload_image_hint' => 'Tora kana sarudza mufananidzo wakajeka weshizha kuti AI ibatsire kuona chirwere.',
                'view_history_hint' => 'Ona mhedzisiro dzakapfuura, chivimbo chemhinduro, uye kurudziro.',
                'crop_library_hint' => 'Tarisa zvirimwa zvinotsigirwa, zviratidzo, kudzivirira, uye marapirwo.',
                'profile_hint' => 'Gadzirisa ruzivo rwako, nhamba yefoni, uye mutauro waunoda.',
                'logout_hint' => 'Vhara chikamu ichi kana wapedza kushandisa sisitimu.',
                'recent_diagnoses' => 'Ongororo dzichangobva kuitwa',
                'no_diagnoses' => 'Hapana ongororo parizvino. Tanga nekuisa mufananidzo wakajeka weshizha.',
                'date' => 'Zuva',
                'crop' => 'Chirimwa',
                'disease' => 'Chirwere',
                'confidence' => 'Chivimbo',
                'open' => 'Vhura',
                'upload_crop_image' => 'Isa mufananidzo wechirimwa',
                'upload_intro' => 'Sarudza mufananidzo wakajeka weshizha rine dambudziko. JPG, PNG, neWEBP kusvika pa5 MB zvinotenderwa.',
                'first_matching_crop' => 'Rega sisitimu ishandise chirimwa chinoenderana chekutanga',
                'leaf_image' => 'Mufananidzo weshizha',
                'run_diagnosis' => 'Tanga kuongorora',
                'disclaimer' => 'Mhedzisiro iyi inobatsira pakusarudza zvekuita mumunda asi haitsvivi zano renyanzvi yezvekurima.',
                'diagnosis_history' => 'Nhoroondo yekuongororwa',
                'history_intro' => 'Sefa ongororo dzakapfuura nechirimwa, chirwere, kana zuva.',
                'all_crops' => 'Zvirimwa zvese',
                'all_diseases' => 'Zvirwere zvese',
                'all_dates' => 'Mazuva ese',
                'today' => 'Nhasi',
                'last_7_days' => 'Mazuva manomwe apfuura',
                'apply_filters' => 'Shandisa mafirita',
                'no_matching_diagnoses' => 'Hapana ongororo inoenderana yawawanikwa.',
                'uploaded_image' => 'Mufananidzo wawakaisa',
                'recommendation' => 'Kurudziro',
                'low_confidence' => 'Chivimbo chakaderera',
                'low_confidence_advice' => 'Tora mufananidzo zvakare muchiedza chakanaka kana kubvunza nyanzvi yezvekurima.',
                'upload_another' => 'Isa mumwe mufananidzo',
                'back_to_history' => 'Dzokera kunhoroondo',
                'crop_library_intro' => 'Tarisa zvirimwa zvinotsigirwa, zviratidzo zvezvirwere, nzira dzekudzivirira, uye marapirwo.',
                'symptoms' => 'Zviratidzo',
                'prevention' => 'Kudzivirira',
                'profile_intro' => 'Gadzirisa ruzivo rwako semurimi uye mutauro waunoda.',
                'profile_updated' => 'Nhoroondo yako yagadziridzwa zvakanaka.',
                'full_name' => 'Zita rakazara',
                'email_address' => 'Email',
                'phone_number' => 'Nhamba yefoni',
                'preferred_language' => 'Mutauro waunoda',
                'english' => 'Chirungu',
                'shona' => 'Shona',
                'save_profile' => 'Chengetedza',
                'unknown_crop' => 'Chirimwa chisingazivikanwi',
            ],
        ];

        return $translations[$language][$key] ?? $translations['en'][$key] ?? $key;
    }
}
